# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_url', models.URLField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeaturedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=450, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_profile_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('youtube_profile_url', models.URLField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(max_length=1500)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('featured_category', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='videos', to='curated_videos.Category')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curated_videos.Conference')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curated_videos.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homefeaturedvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curated_videos.Video'),
        ),
    ]
