# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slug',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
    ]
