# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curated_videos', '0003_category_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(default='tkwZ1jG3XgA', max_length=200),
            preserve_default=False,
        ),
    ]
